//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTPServiceTester.PaymentProcessorHTTPService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentTransaction", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaymentTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TransactionIDField;
        
        private double TransactionAmountField;
        
        private double PaymentAmountField;
        
        private int TenderTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((this.TransactionIDField.Equals(value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double TransactionAmount {
            get {
                return this.TransactionAmountField;
            }
            set {
                if ((this.TransactionAmountField.Equals(value) != true)) {
                    this.TransactionAmountField = value;
                    this.RaisePropertyChanged("TransactionAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double PaymentAmount {
            get {
                return this.PaymentAmountField;
            }
            set {
                if ((this.PaymentAmountField.Equals(value) != true)) {
                    this.PaymentAmountField = value;
                    this.RaisePropertyChanged("PaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TenderType {
            get {
                return this.TenderTypeField;
            }
            set {
                if ((this.TenderTypeField.Equals(value) != true)) {
                    this.TenderTypeField = value;
                    this.RaisePropertyChanged("TenderType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProcessResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentProcessorHTTPService.IPaymentProcessor")]
    public interface IPaymentProcessor {
        
        // CODEGEN: Generating message contract since element name transaction from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentProcessor/Process", ReplyAction="http://tempuri.org/IPaymentProcessor/ProcessResponse")]
        HTTPServiceTester.PaymentProcessorHTTPService.ProcessResponse Process(HTTPServiceTester.PaymentProcessorHTTPService.ProcessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentProcessor/Process", ReplyAction="http://tempuri.org/IPaymentProcessor/ProcessResponse")]
        System.Threading.Tasks.Task<HTTPServiceTester.PaymentProcessorHTTPService.ProcessResponse> ProcessAsync(HTTPServiceTester.PaymentProcessorHTTPService.ProcessRequest request);
        
        // CODEGEN: Generating message contract since element name transactions from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentProcessor/ProcessBatch", ReplyAction="http://tempuri.org/IPaymentProcessor/ProcessBatchResponse")]
        HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchResponse ProcessBatch(HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentProcessor/ProcessBatch", ReplyAction="http://tempuri.org/IPaymentProcessor/ProcessBatchResponse")]
        System.Threading.Tasks.Task<HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchResponse> ProcessBatchAsync(HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Process", Namespace="http://tempuri.org/", Order=0)]
        public HTTPServiceTester.PaymentProcessorHTTPService.ProcessRequestBody Body;
        
        public ProcessRequest() {
        }
        
        public ProcessRequest(HTTPServiceTester.PaymentProcessorHTTPService.ProcessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HTTPServiceTester.PaymentProcessorHTTPService.PaymentTransaction transaction;
        
        public ProcessRequestBody() {
        }
        
        public ProcessRequestBody(HTTPServiceTester.PaymentProcessorHTTPService.PaymentTransaction transaction) {
            this.transaction = transaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessResponse", Namespace="http://tempuri.org/", Order=0)]
        public HTTPServiceTester.PaymentProcessorHTTPService.ProcessResponseBody Body;
        
        public ProcessResponse() {
        }
        
        public ProcessResponse(HTTPServiceTester.PaymentProcessorHTTPService.ProcessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HTTPServiceTester.PaymentProcessorHTTPService.ProcessResult ProcessResult;
        
        public ProcessResponseBody() {
        }
        
        public ProcessResponseBody(HTTPServiceTester.PaymentProcessorHTTPService.ProcessResult ProcessResult) {
            this.ProcessResult = ProcessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessBatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessBatch", Namespace="http://tempuri.org/", Order=0)]
        public HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchRequestBody Body;
        
        public ProcessBatchRequest() {
        }
        
        public ProcessBatchRequest(HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessBatchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HTTPServiceTester.PaymentProcessorHTTPService.PaymentTransaction[] transactions;
        
        public ProcessBatchRequestBody() {
        }
        
        public ProcessBatchRequestBody(HTTPServiceTester.PaymentProcessorHTTPService.PaymentTransaction[] transactions) {
            this.transactions = transactions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessBatchResponse", Namespace="http://tempuri.org/", Order=0)]
        public HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchResponseBody Body;
        
        public ProcessBatchResponse() {
        }
        
        public ProcessBatchResponse(HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessBatchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HTTPServiceTester.PaymentProcessorHTTPService.ProcessResult[] ProcessBatchResult;
        
        public ProcessBatchResponseBody() {
        }
        
        public ProcessBatchResponseBody(HTTPServiceTester.PaymentProcessorHTTPService.ProcessResult[] ProcessBatchResult) {
            this.ProcessBatchResult = ProcessBatchResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentProcessorChannel : HTTPServiceTester.PaymentProcessorHTTPService.IPaymentProcessor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentProcessorClient : System.ServiceModel.ClientBase<HTTPServiceTester.PaymentProcessorHTTPService.IPaymentProcessor>, HTTPServiceTester.PaymentProcessorHTTPService.IPaymentProcessor {
        
        public PaymentProcessorClient() {
        }
        
        public PaymentProcessorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentProcessorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentProcessorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentProcessorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HTTPServiceTester.PaymentProcessorHTTPService.ProcessResponse HTTPServiceTester.PaymentProcessorHTTPService.IPaymentProcessor.Process(HTTPServiceTester.PaymentProcessorHTTPService.ProcessRequest request) {
            return base.Channel.Process(request);
        }
        
        public HTTPServiceTester.PaymentProcessorHTTPService.ProcessResult Process(HTTPServiceTester.PaymentProcessorHTTPService.PaymentTransaction transaction) {
            HTTPServiceTester.PaymentProcessorHTTPService.ProcessRequest inValue = new HTTPServiceTester.PaymentProcessorHTTPService.ProcessRequest();
            inValue.Body = new HTTPServiceTester.PaymentProcessorHTTPService.ProcessRequestBody();
            inValue.Body.transaction = transaction;
            HTTPServiceTester.PaymentProcessorHTTPService.ProcessResponse retVal = ((HTTPServiceTester.PaymentProcessorHTTPService.IPaymentProcessor)(this)).Process(inValue);
            return retVal.Body.ProcessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HTTPServiceTester.PaymentProcessorHTTPService.ProcessResponse> HTTPServiceTester.PaymentProcessorHTTPService.IPaymentProcessor.ProcessAsync(HTTPServiceTester.PaymentProcessorHTTPService.ProcessRequest request) {
            return base.Channel.ProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<HTTPServiceTester.PaymentProcessorHTTPService.ProcessResponse> ProcessAsync(HTTPServiceTester.PaymentProcessorHTTPService.PaymentTransaction transaction) {
            HTTPServiceTester.PaymentProcessorHTTPService.ProcessRequest inValue = new HTTPServiceTester.PaymentProcessorHTTPService.ProcessRequest();
            inValue.Body = new HTTPServiceTester.PaymentProcessorHTTPService.ProcessRequestBody();
            inValue.Body.transaction = transaction;
            return ((HTTPServiceTester.PaymentProcessorHTTPService.IPaymentProcessor)(this)).ProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchResponse HTTPServiceTester.PaymentProcessorHTTPService.IPaymentProcessor.ProcessBatch(HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchRequest request) {
            return base.Channel.ProcessBatch(request);
        }
        
        public HTTPServiceTester.PaymentProcessorHTTPService.ProcessResult[] ProcessBatch(HTTPServiceTester.PaymentProcessorHTTPService.PaymentTransaction[] transactions) {
            HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchRequest inValue = new HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchRequest();
            inValue.Body = new HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchRequestBody();
            inValue.Body.transactions = transactions;
            HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchResponse retVal = ((HTTPServiceTester.PaymentProcessorHTTPService.IPaymentProcessor)(this)).ProcessBatch(inValue);
            return retVal.Body.ProcessBatchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchResponse> HTTPServiceTester.PaymentProcessorHTTPService.IPaymentProcessor.ProcessBatchAsync(HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchRequest request) {
            return base.Channel.ProcessBatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchResponse> ProcessBatchAsync(HTTPServiceTester.PaymentProcessorHTTPService.PaymentTransaction[] transactions) {
            HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchRequest inValue = new HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchRequest();
            inValue.Body = new HTTPServiceTester.PaymentProcessorHTTPService.ProcessBatchRequestBody();
            inValue.Body.transactions = transactions;
            return ((HTTPServiceTester.PaymentProcessorHTTPService.IPaymentProcessor)(this)).ProcessBatchAsync(inValue);
        }
    }
}
