//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPTester.TCPPaymentProcessor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentTransaction", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaymentTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TransactionIDField;
        
        private double TransactionAmountField;
        
        private double PaymentAmountField;
        
        private int TenderTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((this.TransactionIDField.Equals(value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double TransactionAmount {
            get {
                return this.TransactionAmountField;
            }
            set {
                if ((this.TransactionAmountField.Equals(value) != true)) {
                    this.TransactionAmountField = value;
                    this.RaisePropertyChanged("TransactionAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double PaymentAmount {
            get {
                return this.PaymentAmountField;
            }
            set {
                if ((this.PaymentAmountField.Equals(value) != true)) {
                    this.PaymentAmountField = value;
                    this.RaisePropertyChanged("PaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TenderType {
            get {
                return this.TenderTypeField;
            }
            set {
                if ((this.TenderTypeField.Equals(value) != true)) {
                    this.TenderTypeField = value;
                    this.RaisePropertyChanged("TenderType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProcessResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TCPPaymentProcessor.IPaymentProcessor")]
    public interface IPaymentProcessor {
        
        // CODEGEN: Generating message contract since element name transaction from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentProcessor/Process", ReplyAction="http://tempuri.org/IPaymentProcessor/ProcessResponse")]
        TCPTester.TCPPaymentProcessor.ProcessResponse Process(TCPTester.TCPPaymentProcessor.ProcessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentProcessor/Process", ReplyAction="http://tempuri.org/IPaymentProcessor/ProcessResponse")]
        System.Threading.Tasks.Task<TCPTester.TCPPaymentProcessor.ProcessResponse> ProcessAsync(TCPTester.TCPPaymentProcessor.ProcessRequest request);
        
        // CODEGEN: Generating message contract since element name transactions from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentProcessor/ProcessBatch", ReplyAction="http://tempuri.org/IPaymentProcessor/ProcessBatchResponse")]
        TCPTester.TCPPaymentProcessor.ProcessBatchResponse ProcessBatch(TCPTester.TCPPaymentProcessor.ProcessBatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentProcessor/ProcessBatch", ReplyAction="http://tempuri.org/IPaymentProcessor/ProcessBatchResponse")]
        System.Threading.Tasks.Task<TCPTester.TCPPaymentProcessor.ProcessBatchResponse> ProcessBatchAsync(TCPTester.TCPPaymentProcessor.ProcessBatchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Process", Namespace="http://tempuri.org/", Order=0)]
        public TCPTester.TCPPaymentProcessor.ProcessRequestBody Body;
        
        public ProcessRequest() {
        }
        
        public ProcessRequest(TCPTester.TCPPaymentProcessor.ProcessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCPTester.TCPPaymentProcessor.PaymentTransaction transaction;
        
        public ProcessRequestBody() {
        }
        
        public ProcessRequestBody(TCPTester.TCPPaymentProcessor.PaymentTransaction transaction) {
            this.transaction = transaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessResponse", Namespace="http://tempuri.org/", Order=0)]
        public TCPTester.TCPPaymentProcessor.ProcessResponseBody Body;
        
        public ProcessResponse() {
        }
        
        public ProcessResponse(TCPTester.TCPPaymentProcessor.ProcessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCPTester.TCPPaymentProcessor.ProcessResult ProcessResult;
        
        public ProcessResponseBody() {
        }
        
        public ProcessResponseBody(TCPTester.TCPPaymentProcessor.ProcessResult ProcessResult) {
            this.ProcessResult = ProcessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessBatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessBatch", Namespace="http://tempuri.org/", Order=0)]
        public TCPTester.TCPPaymentProcessor.ProcessBatchRequestBody Body;
        
        public ProcessBatchRequest() {
        }
        
        public ProcessBatchRequest(TCPTester.TCPPaymentProcessor.ProcessBatchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessBatchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCPTester.TCPPaymentProcessor.PaymentTransaction[] transactions;
        
        public ProcessBatchRequestBody() {
        }
        
        public ProcessBatchRequestBody(TCPTester.TCPPaymentProcessor.PaymentTransaction[] transactions) {
            this.transactions = transactions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessBatchResponse", Namespace="http://tempuri.org/", Order=0)]
        public TCPTester.TCPPaymentProcessor.ProcessBatchResponseBody Body;
        
        public ProcessBatchResponse() {
        }
        
        public ProcessBatchResponse(TCPTester.TCPPaymentProcessor.ProcessBatchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessBatchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCPTester.TCPPaymentProcessor.ProcessResult[] ProcessBatchResult;
        
        public ProcessBatchResponseBody() {
        }
        
        public ProcessBatchResponseBody(TCPTester.TCPPaymentProcessor.ProcessResult[] ProcessBatchResult) {
            this.ProcessBatchResult = ProcessBatchResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentProcessorChannel : TCPTester.TCPPaymentProcessor.IPaymentProcessor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentProcessorClient : System.ServiceModel.ClientBase<TCPTester.TCPPaymentProcessor.IPaymentProcessor>, TCPTester.TCPPaymentProcessor.IPaymentProcessor {
        
        public PaymentProcessorClient() {
        }
        
        public PaymentProcessorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentProcessorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentProcessorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentProcessorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCPTester.TCPPaymentProcessor.ProcessResponse TCPTester.TCPPaymentProcessor.IPaymentProcessor.Process(TCPTester.TCPPaymentProcessor.ProcessRequest request) {
            return base.Channel.Process(request);
        }
        
        public TCPTester.TCPPaymentProcessor.ProcessResult Process(TCPTester.TCPPaymentProcessor.PaymentTransaction transaction) {
            TCPTester.TCPPaymentProcessor.ProcessRequest inValue = new TCPTester.TCPPaymentProcessor.ProcessRequest();
            inValue.Body = new TCPTester.TCPPaymentProcessor.ProcessRequestBody();
            inValue.Body.transaction = transaction;
            TCPTester.TCPPaymentProcessor.ProcessResponse retVal = ((TCPTester.TCPPaymentProcessor.IPaymentProcessor)(this)).Process(inValue);
            return retVal.Body.ProcessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCPTester.TCPPaymentProcessor.ProcessResponse> TCPTester.TCPPaymentProcessor.IPaymentProcessor.ProcessAsync(TCPTester.TCPPaymentProcessor.ProcessRequest request) {
            return base.Channel.ProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCPTester.TCPPaymentProcessor.ProcessResponse> ProcessAsync(TCPTester.TCPPaymentProcessor.PaymentTransaction transaction) {
            TCPTester.TCPPaymentProcessor.ProcessRequest inValue = new TCPTester.TCPPaymentProcessor.ProcessRequest();
            inValue.Body = new TCPTester.TCPPaymentProcessor.ProcessRequestBody();
            inValue.Body.transaction = transaction;
            return ((TCPTester.TCPPaymentProcessor.IPaymentProcessor)(this)).ProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCPTester.TCPPaymentProcessor.ProcessBatchResponse TCPTester.TCPPaymentProcessor.IPaymentProcessor.ProcessBatch(TCPTester.TCPPaymentProcessor.ProcessBatchRequest request) {
            return base.Channel.ProcessBatch(request);
        }
        
        public TCPTester.TCPPaymentProcessor.ProcessResult[] ProcessBatch(TCPTester.TCPPaymentProcessor.PaymentTransaction[] transactions) {
            TCPTester.TCPPaymentProcessor.ProcessBatchRequest inValue = new TCPTester.TCPPaymentProcessor.ProcessBatchRequest();
            inValue.Body = new TCPTester.TCPPaymentProcessor.ProcessBatchRequestBody();
            inValue.Body.transactions = transactions;
            TCPTester.TCPPaymentProcessor.ProcessBatchResponse retVal = ((TCPTester.TCPPaymentProcessor.IPaymentProcessor)(this)).ProcessBatch(inValue);
            return retVal.Body.ProcessBatchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCPTester.TCPPaymentProcessor.ProcessBatchResponse> TCPTester.TCPPaymentProcessor.IPaymentProcessor.ProcessBatchAsync(TCPTester.TCPPaymentProcessor.ProcessBatchRequest request) {
            return base.Channel.ProcessBatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCPTester.TCPPaymentProcessor.ProcessBatchResponse> ProcessBatchAsync(TCPTester.TCPPaymentProcessor.PaymentTransaction[] transactions) {
            TCPTester.TCPPaymentProcessor.ProcessBatchRequest inValue = new TCPTester.TCPPaymentProcessor.ProcessBatchRequest();
            inValue.Body = new TCPTester.TCPPaymentProcessor.ProcessBatchRequestBody();
            inValue.Body.transactions = transactions;
            return ((TCPTester.TCPPaymentProcessor.IPaymentProcessor)(this)).ProcessBatchAsync(inValue);
        }
    }
}
